
package cz.cvut.fel.sep.klimefi1.semestral.ws.customerDatabase;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.math.BigInteger;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-03T15:27:29.280+01:00
 * Generated source version: 3.1.8
 * 
 */
public final class CustomerDatabaseWSDL_CustomerDatabaseSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.cvut.cz/FEL/", "CustomerDatabase");

    private CustomerDatabaseWSDL_CustomerDatabaseSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerDatabase.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerDatabase ss = new CustomerDatabase(wsdlURL, SERVICE_NAME);
        CustomerDatabaseWSDL port = ss.getCustomerDatabaseSOAP();  
        
        {
        System.out.println("Invoking readCustomerDetails...");
        BigInteger _readCustomerDetails_idVal = new BigInteger("0");
        Holder<BigInteger> _readCustomerDetails_id = new Holder<BigInteger>(_readCustomerDetails_idVal);
        Holder<java.lang.String> _readCustomerDetails_status = new Holder<java.lang.String>();
        Holder<cz.cvut.fel.sep.klimefi1.semestral.ws.customerDatabase.CustomerDetailType> _readCustomerDetails_customer = new Holder<cz.cvut.fel.sep.klimefi1.semestral.ws.customerDatabase.CustomerDetailType>();
        port.readCustomerDetails(_readCustomerDetails_id, _readCustomerDetails_status, _readCustomerDetails_customer);

        System.out.println("readCustomerDetails._readCustomerDetails_id=" + _readCustomerDetails_id.value);
        System.out.println("readCustomerDetails._readCustomerDetails_status=" + _readCustomerDetails_status.value);
        System.out.println("readCustomerDetails._readCustomerDetails_customer=" + _readCustomerDetails_customer.value);

        }
        {
        System.out.println("Invoking readAllCustomers...");
        BigInteger _readAllCustomers_from = new BigInteger("0");
        BigInteger _readAllCustomers_count = new BigInteger("0");
        java.util.List<cz.cvut.fel.sep.klimefi1.semestral.ws.customerDatabase.CustomerType> _readAllCustomers__return = port.readAllCustomers(_readAllCustomers_from, _readAllCustomers_count);
        System.out.println("readAllCustomers.result=" + _readAllCustomers__return);


        }
        {
        System.out.println("Invoking createCustomerChangeOrder...");
        cz.cvut.fel.sep.klimefi1.semestral.ws.customerDatabase.CreateCustomerChangeOrder _createCustomerChangeOrder_parameters = null;
        java.lang.Object _createCustomerChangeOrder__return = port.createCustomerChangeOrder(_createCustomerChangeOrder_parameters);
        System.out.println("createCustomerChangeOrder.result=" + _createCustomerChangeOrder__return);


        }

        System.exit(0);
    }

}
